# Generated by Django 3.2.8 on 2021-11-16 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_criado_em_tarefa_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_expiracao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
