# Generated by Django 3.2.8 on 2021-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tarefa_data_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_expiracao',
            field=models.DateTimeField(),
        ),
    ]
